name: 'Push to Github Packages'

on:
    pull_request:
        types: closed
        branches:
            - main

jobs:
    push_to_registry:
        name: Push Docker image to GitHub Packages tagged with commit hash.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Push to GitHub Packages
              uses: docker/build-push-action@v1
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  # Uppercase letters are not supported so this is all lowercase
                  repository: ncats-gamma/robokache/build
                  tag_with_sha: true
                  tags: main
