name: 'Push to Github Packages'

on:
    pull_request:
        types: closed
        branches:
            - main

jobs:
    push_to_registry:
        name: Push Docker image to GitHub Packages tagged with commit hash.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Push to GitHub Packages
              uses: docker/build-push-action@v1
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.CR_PAT }}
                  registry: ghcr.io
                  tag_with_sha: true
                  tags: main
